package com.studentperformance.backend.service;

import com.studentperformance.backend.dto.FactorImpact;
import com.studentperformance.backend.dto.ModelPrediction;
import com.studentperformance.backend.dto.PredictionResponse;
import com.studentperformance.backend.dto.StudentProfileRequest;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;
import tools.jackson.databind.ObjectMapper;

import java.io.IOException;
import java.io.OutputStream;
import java.nio.charset.StandardCharsets;
import java.nio.file.Path;
import java.time.Duration;
import java.util.List;
import java.util.concurrent.TimeUnit;

@Service
public class PredictionService {
	private final ObjectMapper objectMapper;
	private final Path projectRoot;
	private final String pythonExecutable;

	public PredictionService(
			ObjectMapper objectMapper,
			@Value("${app.project-root:..}") String projectRoot,
			@Value("${app.python-executable:${PREDICT_PYTHON:python3}}") String pythonExecutable) {
		this.objectMapper = objectMapper;
		this.projectRoot = Path.of(projectRoot).toAbsolutePath().normalize();
		this.pythonExecutable = pythonExecutable;
	}

	public PredictionResponse predict(StudentProfileRequest request) {
		ModelPrediction modelPrediction = runModel(request);
		double score = clamp(round1(modelPrediction.predictedScore()), 0, 100);

		return new PredictionResponse(
				score,
				confidenceFor(score),
				Math.min(99, Math.max(1, (int) Math.round(score * 0.98))),
				gradeFor(score),
				summaryFor(request, score, modelPrediction.modelUsed()),
				recommendationsFor(request, score),
				factorsFor(request),
				modelPrediction.modelUsed());
	}

	public String generateReport(String category, String cohort) {
		return """
				# Student Performance Analytics - Executive Report

				## 1. Scope
				Category: %s
				Cohort: %s

				## 2. Key Cohort Findings
				- Total records analyzed: 6,607 students.
				- Average exam score: 67.2%%.
				- Average attendance: 80.0%%.
				- Attendance has the strongest positive correlation with exam score: 0.58.
				- Hours studied is the next strongest positive signal: 0.45.
				- Previous scores and tutoring sessions show smaller positive relationships: 0.18 and 0.16.
				- The Spring Boot backend is connected to the trained SVR model stored in `models/student_performance_model.pkl`.
				- Predictions use the same feature engineering columns that were created during model training.

				## 3. Intervention Priorities
				1. Track attendance because it is the strongest observed performance signal in the EDA.
				2. Encourage consistent weekly study hours because they correlate positively with exam score.
				3. Use tutoring support for students below target scores, while recognizing it is a secondary signal in this dataset.

				## 4. Platform Note
				This report was generated by the Java Spring Boot backend that powers the dashboard API.
				""".formatted(category, cohort);
	}

	private ModelPrediction runModel(StudentProfileRequest request) {
		Path scriptPath = projectRoot.resolve("Backend/src/main/python/predict.py");
		ProcessBuilder builder = new ProcessBuilder(
				pythonExecutable,
				scriptPath.toString(),
				"--project-root",
				projectRoot.toString());
		builder.redirectErrorStream(false);

		try {
			Process process = builder.start();
			try (OutputStream stdin = process.getOutputStream()) {
				objectMapper.writeValue(stdin, request);
			}

			boolean completed = process.waitFor(Duration.ofSeconds(25).toMillis(), TimeUnit.MILLISECONDS);
			String stdout = new String(process.getInputStream().readAllBytes(), StandardCharsets.UTF_8);
			String stderr = new String(process.getErrorStream().readAllBytes(), StandardCharsets.UTF_8);

			if (!completed) {
				process.destroyForcibly();
				throw new IllegalStateException("Prediction model timed out.");
			}
			if (process.exitValue() != 0) {
				throw new IllegalStateException("Prediction model failed: " + stderr.trim());
			}

			return objectMapper.readValue(stdout, ModelPrediction.class);
		} catch (IOException e) {
			throw new IllegalStateException("Unable to start Python model process. Configure app.python-executable or PREDICT_PYTHON.", e);
		} catch (InterruptedException e) {
			Thread.currentThread().interrupt();
			throw new IllegalStateException("Prediction model interrupted.", e);
		}
	}

	private static List<FactorImpact> factorsFor(StudentProfileRequest request) {
		double attendance = valueOr(request.attendance(), 90);
		double studyHours = valueOr(request.studyHours(), 20);
		double sleepHours = valueOr(request.sleepHours(), 7);
		double previousScore = valueOr(request.previousScore(), 75);

		return List.of(
				new FactorImpact("Attendance", attendance >= 90 ? "High Impact" : "Medium Impact", attendance),
				new FactorImpact("Hours Studied", studyHours >= 20 ? "High Impact" : "Medium Impact", Math.min(100, studyHours * 3)),
				new FactorImpact("Previous Score", previousScore >= 80 ? "High Impact" : "Medium Impact", previousScore),
				new FactorImpact("Sleep Quality", sleepHours >= 7 && sleepHours <= 9 ? "Medium Impact" : "Low Impact", Math.min(100, sleepHours * 12)));
	}

	private static List<String> recommendationsFor(StudentProfileRequest request, double score) {
		double attendance = valueOr(request.attendance(), 90);
		double studyHours = valueOr(request.studyHours(), 20);
		double sleepHours = valueOr(request.sleepHours(), 7);

		if (score >= 85) {
			return List.of(
					"Keep the current study rhythm and use weekly revision to protect the score.",
					"Practice timed mock tests to improve speed and reduce exam-day errors.",
					"Maintain consistent sleep during assessment weeks to support recall.");
		}

		return List.of(
				studyHours < 18 ? "Increase focused weekly study time with short daily blocks." : "Turn study hours into active recall and solved practice sets.",
				attendance < 90 ? "Improve attendance because missed classes are strongly tied to lower exam outcomes." : "Use strong attendance as a base for targeted revision.",
				sleepHours < 7 ? "Raise sleep toward 7-8 hours before exams to improve retention." : "Keep sleep consistent and review difficult topics earlier in the week.");
	}

	private static String summaryFor(StudentProfileRequest request, double score, boolean modelUsed) {
		String source = modelUsed ? "the trained SVR model" : "the prediction service";
		return "Based on attendance of " + round1(valueOr(request.attendance(), 90)) + "%, "
				+ round1(valueOr(request.studyHours(), 20)) + " weekly study hours, and a previous score of "
				+ round1(valueOr(request.previousScore(), 75)) + "%, " + source
				+ " projects an exam score of " + round1(score) + "%.";
	}

	private static String gradeFor(double score) {
		if (score >= 90) return "A+";
		if (score >= 80) return "A";
		if (score >= 70) return "B";
		if (score >= 60) return "C";
		return "D";
	}

	private static double confidenceFor(double score) {
		double distanceFromMiddle = Math.abs(score - 70);
		return clamp(round1(88 + Math.min(9, distanceFromMiddle / 4)), 85, 98);
	}

	private static double valueOr(Double value, double fallback) {
		return value == null ? fallback : value;
	}

	private static double clamp(double value, double min, double max) {
		return Math.max(min, Math.min(max, value));
	}

	private static double round1(double value) {
		return Math.round(value * 10.0) / 10.0;
	}
}
